name: deploy-dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      target: dev
    secrets:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}